config {
  type: "view"
  , schema: "staging_football"
  , description: "tabla vertical de detalles (qualifiers). relacion 1:N con eventos."
  , tags: ["staging"]
}

with 

  final as (
    select
      -- claves de enlace
      json_value(raw_events.payload.matchInfo.id) as match_id
      , json_value(match_events.id) as event_id
      
      -- datos del qualifier
      , json_value(q.id) as qualifier_instance_id
      , cast(json_value(qualifier.qualifierId) as int64) as qualifier_type_id
      , json_value(qualifier.value) as qualifier_value

    from
      `tfm-master-futbol.staging_football.raw_events_events_native` as raw_events_events
      , unnest(json_query_array(raw_events.payload.liveData.event)) as match_events
      , unnest(json_query_array(match_events.qualifier)) as qualifier
  )

select * from final