config {
  type: "view"
  , schema: "staging_football"
  , description: "diccionario de tipos de qualifiers"
  , tags: ["staging"]
}

with

  source as (
    select
      cast(qualifier_type_id as int64) as qualifier_type_id
      , qualifier_type_name
      , values as qualifier_value
      , definition as qualifier_definition
      , category as qualifier_category
      , associated_event_type
    from
      `tfm-master-futbol.staging_football.ref_qualifier_types`
  )

select * from source