name: CI - Dataform (SQL Check)

# Se activa cuando se tocan archivos de Dataform
on:
  push:
    branches: [ "dev", "qa" ]
    paths:
      - 'definitions/**'
      - 'includes/**'
      - 'dataform.json'
      - 'workflow_settings.yaml'
  pull_request:
    branches: [ "dev", "qa" ]
    paths:
      - 'definitions/**'
      - 'includes/**'
      - 'dataform.json'
      - 'workflow_settings.yaml'

jobs:
  dataform-compilation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js (Dataform corre en Node)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dataform CLI
        run: npm i -g @dataform/cli

      - name: Install Project Dependencies
        run: npm install

      - name: 🧪 Run Dataform Compile (Validación de SQL)
        run: dataform compile
        # Si hay un error de sintaxis SQL o referencia rota, esto fallará y pondrá el check en ROJO.